#启动端口号
server:
  port: 8086
# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jay_blog??allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: admin
#mybatis-plus的配置
# 此处有坑 单模块加载也需要配置*(classpath 紧挨着的星) 解决自定义SQL无法执行
mybatis-plus:
  mapper-locations: classpath*:mybatis/mapper/*Mapper.xml


