#启动端口号
server:
  port: 8086
# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jay_blog
    username: root
    password: admin
#mybatis-plus的配置
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml


